version: '3'
services:
    mongo:
      image: mongo:5.0.13
      restart: always
      networks:
        - graylog
      volumes:
        - ./mongo:/data/db 
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
      restart: always
      networks:
        - graylog
      environment:
        - http.host=0.0.0.0
        - transport.host=localhost
        - network.host=0.0.0.0
        - "ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true -Xms512m -Xmx512m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      ports:
        - 9200:9200
        - 9300:9300      
      volumes:
        - ./elastic:/usr/share/elasticsearch/data
    graylog:
      image: graylog/graylog:5.0
      restart: always
      networks:
        - graylog
      environment:
        - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
# Password: admin
        - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
        - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
      volumes:
        - ./graylog:/usr/share/graylog/data/journal
      depends_on:
        - mongo
        - elasticsearch
      ports:
# Graylog web interface and REST API
        - 9000:9000
# Syslog TCP
        - 1514:1514
# Syslog UDP
        - 1514:1514/udp
# GELF TCP
        - 12203:12203
        - 12204:12204
# GELF UDP
        - 12201:12201/udp    
    nginx:
      image: nginx:latest
      ports:
        - 80:80
        #      - 443:443
      restart: always
      networks:
        - graylog
      volumes:
        - ./nginx/conf/:/etc/nginx/conf.d/:ro
networks:
    graylog:
      driver: bridge